# Manifest file that describes kubernetes 'deployments' and supporting 'services'
# for 'auxilliary' components to a fastscore environment
# Microservices included are:
#
# fastscore/model-manage-mysql (as 'database')
# fastscore/kafka (as 'kafka')
# fastscore/influx (as 'influx')
#
# NOTE: All directories mounted in the 'volumeMounts' sections of these deployments are
# required for for services to run
# 
# NOTE: Any secrets or configMaps referred to in this manifest must be created outside of this file by running the appropriate commands
# e.g. `kubectl create secret generic <secretname> --from-file=./path/to/file/containing/secret
# See README.md in this project for more specific information

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: dash
    app: dash
    stack: fastscore
  name: dash
spec:
  ports:
  - name: 8061-tcp
    port: 8061
    protocol: TCP
    targetPort: 8061
  selector:
    service: dash
    app: dash
    stack: fastscore
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dash
  labels:
    service: dash
    app: dash
    stack: fastscore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: dash
        app: dash
        stack: fastscore
    spec:
      containers:
      - name: dash
        image: fastscore/demo-dash:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8061
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
# 'fsGroup' setting is required for permissions to the persistentVolumeClaim
      volumes:
status: {}